# Generated by Django 2.1 on 2018-09-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='location')),
            ],
        ),
        migrations.AddField(
            model_name='license',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='license_db.LicenseLocation'),
            preserve_default=False,
        ),
    ]
